"""
Bootstrap — generate initial secrets for a fresh Somnia deployment.

Called by bootstrap.sh during first install. Generates all infrastructure
secrets and writes them to the configured backend + .env file.

Usage:
    python -m shared.secrets.bootstrap [--backend env|file|1password]

With --backend=file (recommended for OSS):
    1. Generates a Fernet master key
    2. Generates all infrastructure secrets
    3. Encrypts them into /data/config/secrets.enc
    4. Writes .env with SOMNIA_MASTER_KEY and SOMNIA_SECRETS_BACKEND=file
    5. Database URL is constructed from generated credentials

With --backend=env:
    1. Generates all infrastructure secrets
    2. Writes everything directly to .env
    3. No encryption, no master key

Does NOT generate:
    - claude.api_key (user provides this)
    - claude.oauth_token (user provides this)
    - Hook credentials (installed later via Claude)
"""

import os
import secrets
import string
import json
import argparse
from pathlib import Path


# Infrastructure secrets to generate at bootstrap
BOOTSTRAP_SECRETS = {
    "db.password": {"length": 32, "description": "PostgreSQL password"},
    "db.user": {"default": "somnia", "description": "PostgreSQL username"},
    "auth.jwt_secret": {"length": 64, "description": "JWT signing key"},
    "auth.internal_api_key": {"length": 48, "description": "Service-to-service auth"},
}

# .env template — values are filled from generated secrets
ENV_TEMPLATE = """# Somnia — generated by bootstrap
# {timestamp}

# --- Secrets backend ---
SOMNIA_SECRETS_BACKEND={backend}
{master_key_line}

# --- Database ---
POSTGRES_USER={db_user}
POSTGRES_PASSWORD={db_password}

# --- Paths (adjust for your system) ---
SOMNIA_DATA_ROOT=./data
SOMNIA_CONFIG_DIR=./data/config
SOMNIA_WORKSPACES_DIR=./data/workspaces
SOMNIA_REPOS_DIR=./
SOMNIA_OUTPUTS_DIR=./data/outputs
SOMNIA_RUNTIME_DIR=./data/runtime
SOMNIA_DOMAINS_DIR=./data/domains
SOMNIA_DOCUMENTS_DIR=./data/documents

# --- Claude authentication (provide one) ---
# Get an API key from https://console.anthropic.com
# ANTHROPIC_API_KEY=sk-ant-...
# Or use Claude Code OAuth (run: claude auth login)
# CLAUDE_CODE_OAUTH_TOKEN=...

# --- Optional: 1Password (only if SOMNIA_SECRETS_BACKEND=1password) ---
# OP_SERVICE_ACCOUNT_TOKEN=...
# CREDENTIALS_API_KEY=...
"""


def _generate_password(length: int = 32) -> str:
    """Generate a cryptographically secure password."""
    alphabet = string.ascii_letters + string.digits
    return "".join(secrets.choice(alphabet) for _ in range(length))


def _generate_fernet_key() -> str:
    """Generate a Fernet encryption key."""
    from cryptography.fernet import Fernet
    return Fernet.generate_key().decode()


def bootstrap(backend: str = "file", env_path: str = ".env",
              vault_path: str = "/data/config/secrets.enc",
              quiet: bool = False) -> dict:
    """
    Generate initial secrets and write configuration.

    Returns dict of generated secrets (for display/logging).
    """
    from datetime import datetime

    generated = {}

    # Generate infrastructure secrets
    for key, spec in BOOTSTRAP_SECRETS.items():
        if "default" in spec:
            generated[key] = spec["default"]
        else:
            generated[key] = _generate_password(spec.get("length", 32))

    master_key = ""
    master_key_line = "# SOMNIA_MASTER_KEY not needed for env backend"

    if backend == "file":
        # Generate master key and encrypt vault
        master_key = _generate_fernet_key()
        master_key_line = f"SOMNIA_MASTER_KEY={master_key}"

        # Write encrypted vault
        from .backends.file import FileBackend
        fb = FileBackend(vault_path=vault_path, master_key=master_key)
        for key, value in generated.items():
            fb.set(key, value)

        if not quiet:
            print(f"  ✓ Encrypted vault written to {vault_path}")
            print(f"  ✓ {len(generated)} secrets generated")

    elif backend == "env":
        master_key_line = "# SOMNIA_MASTER_KEY not needed for env backend"
        if not quiet:
            print(f"  ✓ {len(generated)} secrets will be written to {env_path}")

    elif backend == "1password":
        master_key_line = "# SOMNIA_MASTER_KEY not needed for 1password backend"
        if not quiet:
            print("  ⚠ 1Password backend selected — secrets must be manually")
            print("    stored in your 1Password vault.")

    # Write .env
    env_content = ENV_TEMPLATE.format(
        timestamp=datetime.now().isoformat(),
        backend=backend,
        master_key_line=master_key_line,
        db_user=generated.get("db.user", "somnia"),
        db_password=generated["db.password"],
    )

    env_file = Path(env_path)
    if env_file.exists():
        backup = env_file.with_suffix(".env.bak")
        env_file.rename(backup)
        if not quiet:
            print(f"  ✓ Existing .env backed up to {backup}")

    env_file.write_text(env_content)
    os.chmod(str(env_file), 0o600)

    if not quiet:
        print(f"  ✓ .env written to {env_path}")

    return {
        "backend": backend,
        "secrets_generated": list(generated.keys()),
        "env_path": str(env_path),
        "vault_path": vault_path if backend == "file" else None,
        "master_key_generated": backend == "file",
    }


def main():
    parser = argparse.ArgumentParser(
        description="Generate initial secrets for a Somnia deployment"
    )
    parser.add_argument(
        "--backend", choices=["env", "file", "1password"],
        default="file",
        help="Secrets backend (default: file)",
    )
    parser.add_argument(
        "--env-path", default=".env",
        help="Path to write .env file (default: .env)",
    )
    parser.add_argument(
        "--vault-path", default="/data/config/secrets.enc",
        help="Path for encrypted vault (file backend only)",
    )
    parser.add_argument(
        "--quiet", action="store_true",
        help="Suppress output",
    )
    args = parser.parse_args()

    print("\n🔐 Somnia Bootstrap — Generating secrets\n")
    result = bootstrap(
        backend=args.backend,
        env_path=args.env_path,
        vault_path=args.vault_path,
        quiet=args.quiet,
    )
    print(f"\n✅ Bootstrap complete ({result['backend']} backend)")
    print("\nNext steps:")
    print("  1. Add your Claude API key to .env (ANTHROPIC_API_KEY=...)")
    print("  2. Run: docker compose up -d")
    print("  3. Connect Claude to Somnia's MCP endpoints")
    print("  4. Say hi — Claude will help with the rest\n")


if __name__ == "__main__":
    main()
